"""create patterns and pattern_yarns tables

Revision ID: 62c3b6acb675
Revises: 05928d7b3dc7
Create Date: 2026-05-04 11:09:54.715854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62c3b6acb675"
down_revision: Union[str, Sequence[str], None] = "05928d7b3dc7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patterns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "craft", sa.Enum("KNITTING", "CROCHET", name="crafttype"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("IMPORTED", "CONFIRMED", name="patternstatus"),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("PDF", "TEXT", "RAVELRY", name="patternsource"),
            nullable=False,
        ),
        sa.Column("cover_image_path", sa.String(), nullable=True),
        sa.Column("ravelry_pattern_id", sa.String(), nullable=True),
        sa.Column("original_file_path", sa.String(), nullable=False),
        sa.Column("parsed_json_path", sa.String(), nullable=True),
        sa.Column("tokens_file_path", sa.String(), nullable=True),
        sa.Column("gauge_stitches", sa.Float(), nullable=True),
        sa.Column("gauge_rows", sa.Float(), nullable=True),
        sa.Column("gauge_size", sa.Float(), nullable=True),
        sa.Column("gauge_unit", sa.Enum("CM", "INCH", name="gaugeunit"), nullable=True),
        sa.Column("needle_size", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pattern_yarns",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pattern_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(), nullable=True),
        sa.Column(
            "yarn_weight",
            sa.Enum("LACE", "FINGERING", "DK", "ARAN", "BULKY", name="yarnweight"),
            nullable=True,
        ),
        sa.Column("meters_per_unit", sa.Float(), nullable=True),
        sa.Column("grams_per_unit", sa.Float(), nullable=True),
        sa.Column("grams_needed", sa.Float(), nullable=True),
        sa.Column("strands", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pattern_id"],
            ["patterns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pattern_yarns")
    op.drop_table("patterns")
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS yarnweight")
    op.execute("DROP TYPE IF EXISTS gaugeunit")
    op.execute("DROP TYPE IF EXISTS patternsource")
    op.execute("DROP TYPE IF EXISTS patternstatus")
    op.execute("DROP TYPE IF EXISTS crafttype")
