"""create abbreviations table

Revision ID: adb51820c83b
Revises: e6f7a8b9c0d1
Create Date: 2026-05-19 19:52:23.500273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "adb51820c83b"
down_revision: Union[str, Sequence[str], None] = "e6f7a8b9c0d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abbreviations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("abbreviation", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "STITCH",
                "DECREASE",
                "INCREASE",
                "TECHNIQUE",
                "CONSTRUCTION",
                "YARN_HANDLING",
                "MARKER",
                "PATTERN_STRUCTURE",
                "OTHER",
                name="abbreviationtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "craft",
            sa.Enum("KNITTING", "CROCHET", name="abbreviationcraft"),
            nullable=False,
        ),
        sa.Column("video_link", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("abbreviations")
    # ### end Alembic commands ###
